apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lebonflacon-api
  labels:
    app: lebonflacon-api
spec:
  selector:
    matchLabels:
      app: lebonflacon-api
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lebonflacon-api
    spec:
      containers:
      - env:
        - name: BIND_HOST
          valueFrom:
            configMapKeyRef:
              key: BIND_HOST
              name: api-docker-vue-storefront-api-default-env
        - name: ELASTICSEARCH_HOST
          valueFrom:
            configMapKeyRef:
              key: ELASTICSEARCH_HOST
              name: api-docker-vue-storefront-api-default-env
        - name: ELASTICSEARCH_PORT
          valueFrom:
            configMapKeyRef:
              key: ELASTICSEARCH_PORT
              name: api-docker-vue-storefront-api-default-env
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              key: REDIS_HOST
              name: api-docker-vue-storefront-api-default-env
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_PORT
              name: api-docker-vue-storefront-api-default-env
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              key: REDIS_DB
              name: api-docker-vue-storefront-api-default-env
        - name: BIND_PORT
          valueFrom:
            configMapKeyRef:
              key: BIND_PORT
              name: api-docker-vue-storefront-api-default-env
        - name: VS_ENV
          valueFrom:
            configMapKeyRef:
              key: VS_ENV
              name: api-docker-vue-storefront-api-default-env
        image: gcr.io/root-sanctuary-212300/github-mazaleyrat-vue-storefront-api:latest
        name: lebonflacon-api
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/www/dist
          name: app-tmpfs0
      restartPolicy: Always
      imagePullSecrets:
      - name: regsecret
      volumes:
      - emptyDir:
          medium: Memory
        name: app-tmpfs0
