apiVersion: v1
data:
  BIND_HOST: www.lebonflacon.com
  NODE_CONFIG_ENV: docker
  PM2_ARGS: --no-daemon
  VS_ENV: dev
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app-docker-vue-storefront-default-env
  name: app-docker-vue-storefront-default-env
