apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-prod-cert
  namespace: default
spec:
  secretName: tls-prod-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: app.lebonflacon.com
  acme:
    config:
    - http01: {}
      domains:
      - app.lebonflacon.com
